spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master   #仓库分支
      server:
        git:
          uri: https://github.com/zcloudfly/HelloSpringCloudDemo.git #仓库地址
          search-paths: respo/application-config   #地址里的目录
          username:  920869693@qq.com           #登录名
          password:  zhangyunfei222           #登录密码

server:
  port: 8888   #改想端口  要需 新建 bootstrap.properties  在里面改

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/